services:
    rustapp:
        build:
            dockerfile: Dockerfile
        depends_on:
            - redis

    redis:
        image: redis:latest
        volumes:
            - ./redis_data:/data
